Repository m-lab/prometheus-support, pull requests merged in 2018-10, with the labels that each got.

#322 Add static config for sending alerts from Prometheus to Alertmanager.
  config/federation/prometheus/prometheus.yml.template
Labels: enhancement

#324 Add configmap-reload sidecar for data-processing-cluster prometheus instance
  k8s/data-processing-cluster/deployments/prometheus.yml
Labels: Sprint 17, Task

#327 Sandbox initcontainer improvements
  k8s/prometheus-federation/deployments/prometheus.yml
Labels: enhancement

#330 Add downloader dashboard
  config/federation/grafana/dashboards/Alert_DownloaderIsFailingToUpdate.json
  config/federation/prometheus/alerts.yml
Labels: Sprint 18

#331 Add dashboards for Gardner & Parsers
  config/federation/grafana/dashboards/NDT_EarlyWarning.json
  config/federation/grafana/dashboards/Pipeline_Gardener.json
  config/federation/grafana/dashboards/Pipeline_Parser.json
Labels: Sprint 18, Task

#336 Add SLO panel to Gardener, use increase for hourly and daily
  config/federation/grafana/dashboards/Pipeline_Gardener.json
Labels: Sprint 18, Task

#337 add sawtooth task date graph
  config/federation/grafana/dashboards/Pipeline_Gardener.json
Labels: Sprint 18

#338 Add Gardener_ParseTimeDifferenceTooOld alert
  apply-global-prometheus.sh
  config/federation/alertmanager/config.yml.template
  config/federation/bigquery/bq_gardener_parse_time.sql.template
  config/federation/prometheus/alerts.yml
  k8s/prometheus-federation/deployments/bigquery-exporter.yml
Labels: Sprint 18

#341 Add cadvisor for per-container or per-pod resource utilization
  k8s/prometheus-federation/deployments/cadvisor.yml
Labels: Sprint 19, Task

#344 Alertmanager configs for local testing
  config/local/alertmanager/README.md
  config/local/alertmanager/local.yml
  config/local/alertmanager/send_alerts.sh
Labels: Sprint 19

#345 Upgrade Alertmanager, Add Slack buttons, normalize Alert annotations
  config/federation/alertmanager/config.yml.template
  config/federation/prometheus/alerts.yml
  k8s/prometheus-federation/deployments/alertmanager.yml
Labels: Sprint 19

#351 Update format and make templates more readable
  config/federation/alertmanager/config.yml.template
Labels: Sprint 19, Task

#355 Update cloud console links
  config/federation/grafana/dashboards/Pipeline_Batch.json
  config/federation/grafana/dashboards/Pipeline_Batch_Throughput.json
  config/federation/grafana/dashboards/Pipeline_NDT.json
Labels: Sprint 19, Task

#358 Deploy grafana dashboards to prod on merge with master
  .travis.yml
  apply-global-prometheus.sh
  apply-grafana-dashboards.sh
Labels: Sprint 19, Task

#357 Add reprocessing period bar chart - update byte & file rate panels
  config/federation/grafana/dashboards/Pipeline_Gardener.json
Labels: Sprint 19, Task
