Repository m-lab/prometheus-support, pull requests merged in 2018-06, with the labels that each got.

#237 Add week-over-week panel for global ndt test rate
  config/federation/grafana/dashboards/NDT_GlobalTestRate.json
Labels: Sprint 10, Task

#244 Increase prometheus server RAM by 2GB in staging & oti
  k8s/prometheus-federation/mlab-oti.yml
  k8s/prometheus-federation/mlab-staging.yml
Labels: Sprint 10

#249 Increase RAM to 2x target heap size to prevent OOMs
  k8s/prometheus-federation/mlab-oti.yml
  k8s/prometheus-federation/mlab-staging.yml
Labels: Sprint 11

#250 Add the node-exporter DaemonSet to prometheus cluster
  k8s/prometheus-federation/deployments/node-exporter.yml
Labels: Sprint 11

#251 Scrape the github receiver
  k8s/prometheus-federation/deployments/github-receiver.yml
Labels: Sprint 11

#253 Add stackdriver exporter for mlab-ns
  apply-global-prometheus.sh
  k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
Labels: Sprint 11

#256 Add instance RAM & Datastore metrics for mlab-ns
  k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
Labels: Sprint 11

#258 Update Prometheus SelfMonitoring & add mlabns_Stackdriver Dashboards
  config/federation/grafana/dashboards/MLABNS_Stackdriver.json
  config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
Labels: Sprint 11

#264 Add configmap-reload to Prometheus deployment.
  apply-global-prometheus.sh
  k8s/prometheus-federation/deployments/prometheus.yml
Labels: enhancement
