Repository m-lab/prometheus-support, pull requests merged in 2018-09, with the labels that each got.

#301 Alert for ETL panics & increase timeout for SnmpScrapingDownAtSite
  config/federation/prometheus/alerts.yml
Labels: Sprint 15

#302 Add new alert for the annotator
  config/federation/prometheus/alerts.yml
Labels: Sprint 15

#303 Add bq_ndt_annotation query and alert
  config/federation/bigquery/bq_ndt_annotation.sql
  config/federation/prometheus/alerts.yml
  k8s/prometheus-federation/deployments/bigquery-exporter.yml
Labels: Sprint 15

#304 Sandbox prometheus 2.x dataprocessing upgrade
  k8s/data-processing-cluster/deployments/prometheus.yml
Labels: enhancement

#320 Update deployment relabel rule to distinguish DaemonSet & ReplicaSet
  config/cluster/prometheus/prometheus.yml
  config/federation/prometheus/prometheus.yml.template
Labels: Sprint 17
